version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    # volumes:
    #   - "./app:/var/www/html/app"
    #   - "./config:/var/www/html/config"
    #   - "./routes:/var/www/html/routes"
    #   - "./resources:/var/www/html/resources"
    #   - "./public:/var/www/html/public"
    tty: true
    links:
      - db:todo-db
    container_name: todo-web
    depends_on:
      - db
  db:
    image: mysql:5.7.9
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
    # volumes:
    #    - ${HOME}/.dockerfs/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: todos
    container_name: todo-db
